import{a as L,S as w,i as n}from"./assets/vendor-BK_rxH-O.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))l(r);new MutationObserver(r=>{for(const o of r)if(o.type==="childList")for(const u of o.addedNodes)u.tagName==="LINK"&&u.rel==="modulepreload"&&l(u)}).observe(document,{childList:!0,subtree:!0});function s(r){const o={};return r.integrity&&(o.integrity=r.integrity),r.referrerPolicy&&(o.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?o.credentials="include":r.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function l(r){if(r.ep)return;r.ep=!0;const o=s(r);fetch(r.href,o)}})();const v=L.create({baseURL:"https://pixabay.com/api/",headers:{},params:{key:"51716967-7d1f105da1ec22b798b2084bf",q:"",image_type:"photo",orientation:"horizontal",safesearch:"true"}});async function m(e,t){return(await v.get("",{params:{per_page:15,q:e,page:t}})).data}const g=new w(".gallery a",{captionsData:"alt"});function S(e){const t=document.querySelector(".gallery"),s=e.map(l=>y(l)).join("");t.innerHTML=s,g.refresh()}function C(e){const t=document.querySelector(".gallery"),s=e.map(l=>y(l)).join("");t.insertAdjacentHTML("beforeend",s),g.refresh()}function q(){const e=document.querySelector(".gallery");e.innerHTML=""}function p(){const e=document.querySelector(".loader");e.style.display="block"}function c(){const e=document.querySelector(".loader");e.style.display="none"}function y(e){return`<li><div class="image-box">
  <a href="${e.largeImageURL}"><img src="${e.webformatURL}" alt="${e.tags}"></a>
  <div class="image-description">
    <p class="image-stats">Downloads: ${e.downloads}</p>
    <p class="image-stats">Likes: ${e.likes}</p>
    <p class="image-stats">Views: ${e.views}</p>
    <p class="image-stats">Comments: ${e.comments}</p>
  </div>
</div></li>`}function k(){document.querySelector(".loadmore-js").classList.add("loadmore")}function h(){document.querySelector(".loadmore-js").classList.remove("loadmore")}const f={form:document.querySelector(".form"),gallery:document.querySelector(".gallery"),loadmore:document.querySelector(".loadmore-js")};let a=1,d,i;f.form.addEventListener("submit",O);f.loadmore.addEventListener("click",$);async function O(e){if(e.preventDefault(),d=f.form.elements.searchtext.value,a=1,d.trim()===""){n.show({title:"Oi!",message:"Please enter a valid search option.",backgroundColor:"#fff0f6",titleColor:"#ff4d79",messageColor:"#ff80a0",progressBarColor:"#ffb3c6"}),e.target.reset();return}q(),h(),p();try{const t=await m(d,a);if(i=Math.ceil(t.totalHits/15),t.hits.length===0){n.show({title:"Oops!",message:"Sorry, there are no images matching your search query. Please try again!",backgroundColor:"#fff0f6",titleColor:"#ff4d79",messageColor:"#ff80a0",progressBarColor:"#ffb3c6"}),c(),e.target.reset();return}else S(t.hits),c(),b()}catch{i=0,n.error({message:"ERROR"}),c(),e.target.reset()}}async function $(e){e.preventDefault(),a+=1,p(),b();const t=await m(d,a);try{c(),C(t.hits),f.gallery.lastElementChild.previousElementSibling.scrollIntoView({behavior:"smooth",block:"start"})}catch{n.error({message:"ERROR"}),c(),e.target.reset()}}function b(){if(i>a)console.log(`checked pages, page - ${a}`),console.log(`checked pages, max pages - ${i}`),k();else if(a===i){h(),n.show({message:"We are sorry, but you have reached the end of search results.",backgroundColor:"#fff0f6",titleColor:"#ff4d79",messageColor:"#ff80a0",progressBarColor:"#ffb3c6"});return}}
//# sourceMappingURL=index.js.map
