import{a as b,S as L,i}from"./assets/vendor-BK_rxH-O.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))s(r);new MutationObserver(r=>{for(const o of r)if(o.type==="childList")for(const c of o.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&s(c)}).observe(document,{childList:!0,subtree:!0});function a(r){const o={};return r.integrity&&(o.integrity=r.integrity),r.referrerPolicy&&(o.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?o.credentials="include":r.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function s(r){if(r.ep)return;r.ep=!0;const o=a(r);fetch(r.href,o)}})();const v=b.create({baseURL:"https://pixabay.com/api/",headers:{},params:{key:"51716967-7d1f105da1ec22b798b2084bf",q:"",image_type:"photo",orientation:"horizontal",safesearch:"true"}});async function u(e,t){return(await v.get("",{params:{per_page:15,q:e,page:t}})).data}const m=new L(".gallery a",{captionsData:"alt"});function w(e){const t=document.querySelector(".gallery"),a=e.map(s=>y(s)).join("");t.innerHTML=a,m.refresh()}function S(e){const t=document.querySelector(".gallery"),a=e.map(s=>y(s)).join("");t.insertAdjacentHTML("beforeend",a),m.refresh()}function q(){const e=document.querySelector(".gallery");e.innerHTML=""}function C(){const e=document.querySelector(".loader");e.style.display="block"}function d(){const e=document.querySelector(".loader");e.style.display="none"}function y(e){return`<li><div class="image-box">
  <a href="${e.largeImageURL}"><img src="${e.webformatURL}" alt="${e.tags}"></a>
  <div class="image-description">
    <p class="image-stats">Downloads: ${e.downloads}</p>
    <p class="image-stats">Likes: ${e.likes}</p>
    <p class="image-stats">Views: ${e.views}</p>
    <p class="image-stats">Comments: ${e.comments}</p>
  </div>
</div></li>`}function M(){document.querySelector(".loadmore-js").classList.add("loadmore")}function g(){document.querySelector(".loadmore-js").classList.remove("loadmore")}const f={form:document.querySelector(".form"),gallery:document.querySelector(".gallery"),loadmore:document.querySelector(".loadmore-js")};let l=1,n,p;f.form.addEventListener("submit",x);f.loadmore.addEventListener("click",O);async function x(e){if(e.preventDefault(),n=f.form.elements.searchtext.value,l=1,n.trim()===""){i.show({title:"Oi!",message:"Please enter a valid search option.",backgroundColor:"#fff0f6",titleColor:"#ff4d79",messageColor:"#ff80a0",progressBarColor:"#ffb3c6"}),e.target.reset();return}q(),g(),C();try{const t=await u(n,l);if(p=Math.ceil(t.totalHits/15),t.hits.length===0){i.show({title:"Oops!",message:"Sorry, there are no images matching your search query. Please try again!",backgroundColor:"#fff0f6",titleColor:"#ff4d79",messageColor:"#ff80a0",progressBarColor:"#ffb3c6"}),d(),e.target.reset();return}else w(t.hits),d(),h()}catch{}}async function O(e){e.preventDefault();const t=await u(n,l);try{h(),S(t.hits),d()}catch{}}function h(){p>l?(l+=1,M()):(g(),i.show({message:"We are sorry, but you have reached the end of search results.",backgroundColor:"#fff0f6",titleColor:"#ff4d79",messageColor:"#ff80a0",progressBarColor:"#ffb3c6"}))}
//# sourceMappingURL=index.js.map
